name: Node Continuous Integration

on: 
  push:
    branches: [ master ]

jobs:
  test_push_build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version:
          - 12
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm test
      - run: npm run build
      